### ISSUE TITLE
No note_to_payee in transaction when listing payments

### ISSUE THREAD

**Issue by harounb** [paypal/PayPal-REST-API-issues#150] opened 2017-10-02 09:53 UTC
> For Internal Tracking: PPPLPAYPT-28084
 
`note_to_payee` is missing from [getPayment](https://developer.paypal.com/docs/api/payments/#payment_get) response of [Payment API](https://developer.paypal.com/docs/api/payments/).  

### General information
I'm getting note to payee in the response to my create payment call. However when I do a list on payments it's not being included in that response.
* Environment: Sandbox
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description
- Create payment with note_to_payee as a string under the transaction
- Note that note_to_payee is returned in the payment response
- Do a get on /payments. Find the payment you just created
- Note there is no note_to_payee field shown here

**Comment by xiaoleih41** [comment] 2017-10-02 19:22
@harounb I cannot reproduce this error. When I do a list on payments, i was able to get `note_to_payer` in the response.

**Comment by harounb** [comment] 2017-10-02 22:09
@xiaoleih41 `note_to_payer` is similar but the field that is missing for me is `note_to_payee`.

Besides the difference in name `note_to_payee` is meant to exist under the transactions object and is from the customer to us.

**Comment by xiaoleih41** [comment] 2017-10-03 14:41
@harounb  This is strange. i don't get `note_to_payer` today either.  Yes, the `note_to_payee` was not included in the response either. I am submitting the issue to product team for review.  I will post the updates on this issue going forward.

**Comment by harounb** [comment] 2017-10-03 16:50
Thanks @xiaoleih41. Looking forward to the updates.
That is strange about `note_to_payer` also being gone. You're definitely correct about it being there before, I also checked after you mentioned it.

**Comment by xiaoleih41** [comment] 2017-10-03 18:52
@harounb I was told that PayPal has just deprecated these two fields. The new checkout flow will not support these fields. Please check if you can use 'custom' field as the workaround.

**Comment by harounb** [comment] 2017-10-03 19:56
@xiaoleih41 Ah that's a shame. 
I should have realised since no_notes is being deprecated from the web experience api as well.
I was planning on using these fields as a workaround to that.

Will there be some documentation soon regarding what fields are being deprecated and why?
Using the API these last few days has been quite frustrating, normally if there are large breaking changes incoming to a client facing API there should be some notice given for them before they are removed.

I'll try using custom, although I had already used that field for something else so will require more work.

**Comment by xiaoleih41** [comment] 2017-10-05 15:26
Thank you.  Due to the type of new payment process flow PayPal is using.  it no longer supports these fields. I was told that both will be deprecated to support the new flow.  I am closing this thread as there will be no fix will be done this issue.

**Closed by xiaoleih41** 2017-10-05 15:26 UTC

**Comment by farse** [comment] 2018-10-30 12:35
paypal needs to update it's documentation because the fields are still listed here. oh the pain it creates when you try to use something and it doesn't work.
https://developer.paypal.com/docs/api/payments/v1/#definition-transaction
