### ISSUE TITLE
UNSUPPORTED_PAYEE_CURRENCY although USD is being sent as currency

### ISSUE THREAD

**Issue by nsathyendra** [paypal/PayPal-REST-API-issues#155] opened 2017-10-09 06:50 UTC
* Environment: Production
* `PayPal-Debug-ID` values: No debug IDs
* Language: PHP

### Issue description
Getting UNSUPPORTED_PAYEE_CURRENCY error and users are not able make payment although USD is being sent as the currency. This issue has suddenly cropped. All payments were working fine with the same API request until this issue cropped up.

API request being sent:
`PayPal\Api\Payment Object (
	
	[_propMap:PayPal\Common\PayPalModel:private] => Array (
		
		[redirect_urls] => PayPal\Api\RedirectUrls Object (
			[_propMap:PayPal\Common\PayPalModel:private] => Array (
				[return_url] => http://xxxx.xxx/cart/paypalApiResponse
				[cancel_url] => http://xxxx.xxx/cart/paypalFailedOrder
			)
		)
		
		[intent] => sale
		
		[payer] => PayPal\Api\Payer Object (
			[_propMap:PayPal\Common\PayPalModel:private] => Array (
				[payment_method] => paypal
			)
		)
		
		[transactions] => Array (
			[0] => PayPal\Api\Transaction Object (
				
				[_propMap:PayPal\Common\PayPalModel:private] => Array (
					
					[amount] => PayPal\Api\Amount Object ( 
						
						[_propMap:PayPal\Common\PayPalModel:private] => Array (	
							[total] => 29.00
							[currency] => USD
						)
					)
					
					[description] => 95997
					[related_resources] => Array ()
				)
			)
		)
		
		[id] => XXX-XXXXXXXX
		[state] => created
		[create_time] => 2017-10-08T15:53:32Z
		[links] => Array (
			[0] => PayPal\Api\Links Object (
				[_propMap:PayPal\Common\PayPalModel:private] => Array (
					[href] => https://api.paypal.com/v1/payments/payment/XXX-XXXXXXX
					[rel] => self
					[method] => GET
				)
			)
			
			[1] => PayPal\Api\Links Object (
				[_propMap:PayPal\Common\PayPalModel:private] => Array (
					[href] => https://www.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=XX-XXXXX
					[rel] => approval_url
					[method] => REDIRECT
				)
			)
			
			[2] => PayPal\Api\Links Object (
				[_propMap:PayPal\Common\PayPalModel:private] => Array (
					[href] => https://api.paypal.com/v1/payments/payment/XXX-XXXXX/execute
					[rel] => execute
					[method] => POST
				)
			)
		)
	)
)
`

This goes to: https://www.paypal.com/webapps/hermes/fallback?product=ec&fallback=1&reason=UNSUPPORTED_PAYEE_CURRENCY&token=XX-XXXXX

And then this page is shown: https://i.imgur.com/yRrPZ32.png

**Comment by xiaoleih41** [comment] 2017-10-09 14:22
Please provide `debugId` for us to do troubleshooting.

**Comment by nsathyendra** [comment] 2017-10-10 05:44
@xiaoleih41 no debugID's are generated in the dashboard. They are empty. Do you mean the token=XX-XXXX in the URL provided?

**Comment by xiaoleih41** [comment] 2017-10-10 17:52
As it's a production issue. Out of privacy concern, please contact www.paypal-techsupport.com providing them with your payment token for them to do troubleshooting for you.

**Comment by nsathyendra** [comment] 2017-10-11 05:28
@xiaoleih41  No response from tech support. Already tried. Any guesses on what exactly could be causing the UNSUPPORTED_PAYEE_CURRENCY suddenly?

**Comment by xiaoleih41** [comment] 2017-10-11 18:51
Please give me the techsupport ticket number. I will have them follow up with you. The error message should have been caused by the currency that is not supported in the receiver's account.

**Comment by xiaoleih41** [comment] 2017-10-19 13:38
Close this issue as the solution path has been provided.

**Closed by xiaoleih41** 2017-10-19 13:38 UTC
