### ISSUE TITLE
How to know that a Billing Agreement has outstanding_balance > 0?

### ISSUE THREAD

**Issue by Fruzenshtein** [paypal/PayPal-REST-API-issues#201] opened 2018-02-13 18:36 UTC
Hello dear PayPal Dev team :)

Actually it's clear that I can [get billing agreement details](https://developer.paypal.com/docs/api/payments.billing-agreements#billing-agreements_get) and in the response body I can take a look at `outstanding_balance`.

But what about some webhook which I can handle on my side in case of failed billing agreement payment? Because without a such webhook I must go through all ACTIVE billing agreements of my customers and request info for each of them. 
Hence I generate tones of useless traffic to paypal rest api on daily basis. 

The main goal is to suspend a billing agreement which has positive `outstanding_balance`.

How to handle this?

**Comment by xiaoleih41** [comment] 2018-02-13 19:46
Can you use the webhook, payment.sale.denied.  Once it's denied, it should result an outstanding_balance of that specific billing agreement.

**Comment by Fruzenshtein** [comment] 2018-02-14 07:44
@xiaoleih41 is PAYMENT.SALE.DENIED react on billing agreement payments as well? I thought it is for standalone instant payments, but not for billing agreements O_o

Because I was looking on webhooks from the prefix group BILLING.SUBSCRIPTION.* but have not found anything useful :(

**Comment by xiaoleih41** [comment] 2018-02-14 14:33
Yes, the payment.sale.denied should work with any actual payment going through billing agreement too.

**Comment by Fruzenshtein** [comment] 2018-02-14 14:35
@xiaoleih41 I've already set up the webhook handler, so I'll check it soon and write a result here 👍

**Comment by Fruzenshtein** [comment] 2018-02-14 17:25
@xiaoleih41 I created a billing agreement in prod env with paypal account which does not has enough money
Billing agreement ID: I-E17VB7RJCRAS
But no any webhook PAYMENT.SALE.DENIED happened :(

**Comment by xiaoleih41** [comment] 2018-02-14 18:24
Was transaction failed?  I don't have live access.

**Comment by Fruzenshtein** [comment] 2018-02-14 19:28
According to SMS from my bank - yes
I haven't enough money on my debit card to pay for the subscription
So I believe in terms of PayPal a such case should lead to failed transaction

**Comment by xiaoleih41** [comment] 2018-02-14 20:00
Can you check your PayPal account to see what's the status of that transaction. As it's production account, it may be easier to file a ticket with www.paypal-techsupport.com.

**Comment by Fruzenshtein** [comment] 2018-02-14 20:09
In the Preapproved Payments section I see that the billing agreement is Active, but it has no any transactions at all. 

Also I see that:

Next payment on 14 Feb 2018

But this is a today :D

**Comment by xiaoleih41** [comment] 2018-02-21 15:39
This is an account specific question. I am not able to reproduce from my side. Is it possible you can reach out to developer.paypal.com/contact instead as it doesn't seem to be an SDK issue.

**Comment by xiaoleih41** [comment] 2018-02-23 15:51
Close this issue as it has something to do live account setting and the contact info has been provided.

**Closed by xiaoleih41** 2018-02-23 15:51 UTC
