### ISSUE TITLE
Webhook simulator payment.sale.refunded looks wrong

### ISSUE THREAD

**Issue by jleclanche** [paypal/PayPal-REST-API-issues#136] opened 2017-09-03 01:12 UTC
I just received a webhook of type `payment.sale.refunded` which looks nothing like the one in the webhook simulator. The simulator sends an event_type of `sale`, whereas live sends an event_type `refund`.

**Comment by xiaoleih41** [comment] 2017-09-15 14:51
I am not sure as I checked simulator for `payment.sale.refund` webhook event, it shows. ````"resource_type": "sale",
"event_type": "PAYMENT.SALE.REFUNDED",````

**Comment by xiaoleih41** [comment] 2017-09-18 17:22
Close this issue as we cannot reproduce the error.

**Closed by xiaoleih41** 2017-09-18 17:22 UTC
