### ISSUE TITLE
next_billing_date from the response object after a billing agreement is executed. 

### ISSUE THREAD

**Issue by jleclanche** [paypal/PayPal-REST-API-issues#199] opened 2018-02-06 09:51 UTC
> For Internal Tracking: PPPLPAYPT-33233

* Environment: Production

I was using `next_billing_date` but it's actually inconsistent between the API and the paypal dashboard.

![image](https://user-images.githubusercontent.com/235410/35852494-bc68374e-0b33-11e8-9a0c-1cc9be7e0fa9.png)

Looking at that particular payment, I have no datetime that matches feb 9. I don't really understand where I'm supposed to get that next payment due, or even why there's nothing on the dashboard saying the next billing date is feb 4th.

Are there cases where the next payment isn't gathered on the next billing date?

**Comment by xiaoleih41** [comment] 2018-02-06 20:33
I will report the issue. As it's an production issue, please submit a ticket to www.paypal-techsupport.com to include your live account info. This will help prioritize the issue.

**Comment by xiaoleih41** [comment] 2018-02-08 19:51
@jleclanche  If you try to get the billing agreement again, does it match to the one listed inside of PayPal? What's the billing agreement profile Id of this agreement? If you right click on your PayPal dashboard of that page and click on `view source`, can you please give me the `rlogid`  as well? Please note that make the start date at least 24 hour after the current date. If you are looking for instant payment, you should use `setup_fee` instead.

**Comment by xiaoleih41** [comment] 2018-02-13 15:51
@jleclanche  Was the issue solved? Please help provide additional info or close this issue if it has been solved.

**Comment by jleclanche** [comment] 2018-02-13 18:15
@xiaoleih41 hi, sorry, forgot to reply. No my issue isn't solved, the next_billing_date mismatches the one shown on Paypal for a bunch of billing agreements.
BA in question is `I-1X9BRWUMCWXN`. 
`         rlogid : 5bcfLJpnG5PzqKMjDwHzuA7VvJXS940p3ujPnyhAjvxAr5U9Oiau4g&#x25;3d&#x25;3d&#x5f;161905e7bce`

**Comment by xiaoleih41** [comment] 2018-02-14 16:16
Do you set the start date at least 24 hours after the current date?

**Comment by jleclanche** [comment] 2018-02-14 16:29
Well, here's what my setup is:

- I have two premium plans: one monthly, one semi-annual.
- I want to receive an immediate payment in full in order to unlock the subscription for the user.
- When a user cancels, they remain premium for the remainder of the period.

This was very easy to do in Stripe, however Paypal doesn't support either "bill at beginning of period", or "cancel at period end".

So I did the following:

1. Add a setup_fee equal to the full amount of one cycle of the plan.
2. Set the start date of the plan one billing period ahead (So the plan doesn't start until the period you paid for as part of the setup_fee has lapsed).
3. If you cancel, internally track the billing agreement dates and recognize you as premium until the full period you paid for has lapsed.
4. Keep track of when your next billing period is due and downgrade you if the bill is not paid in time.

For that last bit I use next_billing_date. Or at least I wanted to, but it's super inconsistent, so I have to work around it by adding a margin of error of 2 weeks.

**Comment by xiaoleih41** [comment] 2018-02-14 18:30
As you have set up `setup_fee` as the instant payment to cover the plan activation or first billing cycle payment so I assume the start date of the plan should be at least days after the billing agreement creation date.  the log for the billing agreement has expired from our system. Is it possible you can provide a most recent billing agreement ID that we can take a look?

**Comment by jleclanche** [comment] 2018-02-14 18:45
Not sure how to consistently find these. :/

**Comment by xiaoleih41** [comment] 2018-02-14 20:02
Do you have another agreement with the same issue?

**Comment by jleclanche** [comment] 2018-02-14 20:13
I definitely have more, but I'm not able to programmatically tell if the dates mismatch. The majority of them match so it's hard to find them manually.

**Comment by xiaoleih41** [comment] 2018-02-15 15:16
I think it will be better to open a ticket at www.paypal-techsupport.com as they can access your live account and troubleshoot for you.

**Comment by xiaoleih41** [comment] 2018-02-22 16:57
Close this issue as the suggestion as been made.

**Closed by xiaoleih41** 2018-02-22 16:57 UTC

**Comment by jleclanche** [comment] 2018-02-22 16:59
I mean, it's a problem that your API does not consistently return the correct date there. The date as seen on the dashboard is nowhere to be found in the API...

**Comment by xiaoleih41** [comment] 2018-02-22 17:12
I understand but as I cannot reproduce, I can make the case at this time. Is it possible when you have a new sample you submit a ticket at techsupport and refer to this Jira ticket number for internal reference PPPLPAYPT-33233.
