### ISSUE TITLE
Time format is wrong in the error message when query the list of payment by time ranges in wrong time format. 

### ISSUE THREAD

**Issue by Krazal** [paypal/PayPal-REST-API-issues#141] opened 2017-09-11 09:00 UTC
> for internal tracking: PPPLMER-38392

Time format is wrong in the error message when query the list of payment by time ranges in wrong time format. 
### General information

* Environment: Sandbox
* `PayPal-Debug-ID` values: **90e53ff34e6fa**
* Language, language version, and OS: **PayPal-PHP-SDK-1.12.0**

### Issue description

`An internal service error occurred` when tried to get payments by `start_time` or `end_time` (`urldecode`d format). Using only `count` and `start_index` works like a charm.

**Request:**
```
Array
(
    [start_index] => 1
    [count] => 10
    [start_time] => 2017-09-10T00:00:00+02:00
    [end_time] => 2017-09-11T10:41:02+02:00
)
```

**Response:**
```
{
    "name": "INTERNAL_SERVICE_ERROR",
    "message": "An internal service error occurred.",
    "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR",
    "debug_id": "90e53ff34e6fa"
}
```

**Comment by xiaoleih41** [comment] 2017-09-12 01:53
I just queried a list of payments by `start_time` and `end_time` only using the format `2017-03-06T11:00:00Z` as listed in the [API reference] (https://developer.paypal.com/docs/api/payments/#payment_list). It looks fine.

**Comment by Krazal** [comment] 2017-09-12 10:05
Oh, I found the bug!

I tried the PHP's `date('c')` function, so the result was `2017-09-10T00:00:00+02:00`. After modifying this to `yyyy-mm-ddThh:mm:ssZ` format it worked, so only **the error message was misleading;** I got `Must be a date_time string of form yyyy-mm-ddThh:mm:ss(.sss)?Z` message earlier.

**Comment by xiaoleih41** [comment] 2017-09-13 14:23
I have requested a fix on the error message.

**Comment by xiaoleih41** [comment] 2017-10-16 16:51
Close this issue as the issue is solved.

**Closed by xiaoleih41** 2017-10-16 16:51 UTC
Labels: bug, payments
