### ISSUE TITLE
Transaction ID in Billing agreement API agreement_transaction object

### ISSUE THREAD

**Issue by schmartmann** [paypal/PayPal-REST-API-issues#140] opened 2017-09-10 00:40 UTC
> For internal bookkeeping: PPPLMER-38335

[Billing agreement API](https://developer.paypal.com/docs/api/payments.billing-agreements/?mark=search%20billing%20agreement%20transaction#agreement) [agreement_transaction](https://developer.paypal.com/docs/api/payments.billing-agreements/?mark=search%20billing%20agreement%20transaction#definition-agreement_transaction) object is missing payment transaction identifier. 
### General information

* Environment: Sandbox
* Language, language version, and OS: Ruby SDK

### Issue description
I'm working on recurring payments, and I'm able to successfully create a Billing Plan + Billing Agreements, and even get returned ```PAYMENT.SALE.COMPLETED``` webhooks that have an associated ```billing_agreement_id```. 

I'm stuck on how to retrieve the actual Payment from the PayPal API associated with the ```PAYMENT.SALE.COMPLETED``` webhook event. 

I've used the Billing Agreement's transactions method to return a list of all transactions associated with a billing_agreement, but none of these appear to have a ```PAY-```id, or anything else that would lead me to its corresponding object in the Payments API.

**Comment by xiaoleih41** [comment] 2017-09-12 03:20
I have reported this issue. Please follow this issue for the progress status.

**Comment by schmartmann** [comment] 2017-09-15 19:47
Any updates on this?

**Comment by xiaoleih41** [comment] 2017-09-18 16:46
The issue has been assigned and investigated. I will keep you posted once there's any more progress.

**Comment by xiaoleih41** [comment] 2017-10-31 18:08
@schmartmann Can you check again, It looks like it is fixed. the transaction ID is actually showing the `saleId` which you can retrieve back to the **payment API** object.

**Comment by xiaoleih41** [comment] 2017-11-07 20:34
Closed as the issue is solved.

**Closed by xiaoleih41** 2017-11-07 20:34 UTC
Labels: billing-agreements, bug
