### ISSUE TITLE
GET sale does not include parent_payment field

### ISSUE THREAD

**Issue by matthiassiegel** [paypal/PayPal-REST-API-issues#190] opened 2018-01-26 23:25 UTC
This was originally reported for the [Ruby SDK](https://github.com/paypal/PayPal-Ruby-SDK/issues/333) but seems to be an API bug.

* Environment: Production
* Language: Ruby SDK 1.7.2

According to the [docs](https://developer.paypal.com/docs/api/payments/#sale_get) the sale object should include the ID of the parent payment in a field `parent_payment`.

I tried several sale IDs, both from one-off transactions and transactions that were created through billing agreements, and `parent_payment` is always blank.

```ruby
[2] pry(main)> sale = PayPal::SDK::REST::Sale.find(sale_id)
I, [2018-01-25T11:11:46.644463 #57893]  INFO -- : Request[post]: https://api.paypal.com/v1/oauth2/token
I, [2018-01-25T11:11:47.586357 #57893]  INFO -- : Response[200]: OK, Duration: 0.942s
I, [2018-01-25T11:11:47.594064 #57893]  INFO -- : Request[get]: https://api.paypal.com/v1/payments/sale/(...)
I, [2018-01-25T11:11:48.773545 #57893]  INFO -- : Response[200]: OK, Duration: 1.179s
=> #<PayPal::SDK::REST::DataTypes::Sale:0x00007fbd718e88f8 (...)
[3] pry(main)> sale.parent_payment
=> nil

```

This looks like an API problem. The `parent_payment` field is not included in the API response when querying `https://api.paypal.com/v1/payments/sale/[sale_id]`.

**Comment by xiaoleih41** [comment] 2018-01-29 15:35
The parent payment ID is another sale ID of a different transaction which is associated with this specific transaction.  For example, if you have saleID/transactionId associated with a refund payment, you want to find the original payment transaction ID, you can query that refund payment transactionID and the original sent payment transaction ID should show in the parent payment ID field.

**Comment by xiaoleih41** [comment] 2018-02-01 15:39
Close this issue as the answer has been given.

**Closed by xiaoleih41** 2018-02-01 15:39 UTC
Labels: payments

**Comment by matthiassiegel** [comment] 2018-02-01 22:40
@xiaoleih41 Why was this closed? Your answer describes the expected behaviour, but it doesn't currently work, that's the point of this issue. Please do some testing.

> For example, if you have saleID/transactionId associated with a refund payment, you want to find the original payment transaction ID, you can query that refund payment transactionID and the original sent payment transaction ID should show in the parent payment ID field.

That's exactly what I'm trying to do, but the parent payment ID comes back **blank** from the API. Without supplying the parent payment ID in the sale object there is no way in the API to get to the parent transaction from a sale ID.

Please note that your docs also list another field `purchase_unit_reference_id` on the sale object, which also comes back blank.

<img width="583" alt="screen shot 2018-02-02 at 9 37 35 am" src="https://user-images.githubusercontent.com/132177/35707196-edb1cf34-07fc-11e8-9cd2-33acd95f7145.png">

**Comment by xiaoleih41** [comment] 2018-02-02 20:04
Can you give me a transaction ID sample that you were trying to query?

**Comment by matthiassiegel** [comment] 2018-02-03 01:56
@xiaoleih41 `68S17002HV530892T` and `7SD73661JF856320M`

**Comment by xiaoleih41** [comment] 2018-02-05 18:57
Is this a production only issue as I cannot reproduce this in sandbox. Could you please contact developer.paypal.com/support as they will need to check into your account and file a bug if it is needed.
